### PR TITLE
netlist: Resolve #8590 and fix #r73625467 (#9751), add tests

### LINKED ISSUE #8590: plib/ppmf.h suffers multiple issues
The pointer to member function code in src/lib/netlist/plib/ppmf.h suffers from issues I fixed for src/lib/util/delegate.h in #8589.  This further reinforces my opinion that it’s a bad idea to have so many things reimplemented in the netlist library.  It means more opportunities for bugs, and dual maintenance.

At a glance, I can see the following issues are present:
* Treating `this` pointer displacement as `int` rather than the correct `ptrdiff_t` for Itanium C++ ABI.
* Not right-shifting the `this` pointer displacement for ARM-like Itanium C++ ABI.
* Not applying the `this` pointer displacement for virtual member functions for ARM-like Itanium C++ ABI.
* Incorrectly applying the `this` pointer delta to the vptr for ARM-like Itanium C++ ABI.
* Not considering platforms where function pointers point to function descriptors.

### PR DESCRIPTION
**Pull request by couriersud**
- Fixes compile with apple clang 10
- fix standalone vs 2019 build
- PMF now working properly in VS due to addition of static stub.
- Align syntax in ppmf to MAME delegate.h
  There is one use case in netlist using the protected object function.
  Once this has been removed, netlist can optionally be compiled with
  MAME delegate code.
- Add tests/test_ppmf*.cpp testing examples given in #8590

### CODE REVIEW

**Comment by 0kmg** [comment]
I can confirm this compiles on my end.

File: src/lib/netlist/plib/ptests.h [hunk 1]
```diff
@@ -51,7 +51,7 @@
 
 #define PINT_EXPECT(comp, exp1, exp2) \
 	if (!plib::testing::internal_assert(plib::testing::comp_ ## comp (), # exp1, # exp2, exp1, exp2)) \
-		std::cout << __FILE__ << ":" << __LINE__ << ":1: error: test failed\n"
+		std::cout << std::string(__FILE__) << std::string(":") << __LINE__ << std::string(":1: error: test failed\n")
```
Comment (cuavas) [inline src/lib/netlist/plib/ptests.h:54]: Is there a good reason for constructing `std::string` here?  It potentially causes allocations.

File: src/lib/netlist/plib/ppmf.h [hunk 2]
```diff
@@ -8,28 +8,24 @@
 /// \file ppmf.h
```
Comment (cuavas) [inline src/lib/netlist/plib/ppmf.h:8]: This file seems to have inadvertently had its execute bit set.

File: src/lib/netlist/plib/ppmf.h [hunk 3]
```diff
@@ -38,66 +34,28 @@
 #include <algorithm>
 #include <cstdint> // uintptr_t
 #include <utility>
+#include <type_traits>
```
Comment (cuavas) [inline src/lib/netlist/plib/ppmf.h:37]: These have got out of alphabetical order.

File: src/lib/netlist/core/core_device.h [hunk 4]
```diff
@@ -33,7 +33,7 @@ namespace netlist
 		{
 			gsl_Expects(m_active_outputs >= 0);
 
-			if (m_activate && m_hint_deactivate)
+			if (!m_activate.isnull() && m_hint_deactivate)
```
Comment (cuavas) [inline src/lib/netlist/core/core_device.h:36]: Is there a good reason for avoiding the use of an `explicit operator bool`?  It would be the idiomatic C++ approach for testing if the object is dereferenceable, as used with pointers, various smart pointers (`std::unique_ptr`, `std::shared_ptr`, etc.), `std::optional`, `std::function`, and so on.

**Review by cuavas — COMMENTED** [review]
It’s good if some of the issues in PPMF can be resolved.
* Have you fully exercised this for a target using the ARM variant of the Itanium ABI (e.g. ARM, AArch64, or WebAssembly)?
* At a glance, I didn’t notice provision for targets where function pointers point to descriptors (e.g. AIX/WinNT PPC, Linux/AIX PPC64, Itanium, etc.).  Are you catering for this?
* Did you consider walking resolved PLT entries and out-of-line virtual call stubs used with MSVC ABI to reduce overhead?
* I take it you’ve read [this](https://rants.vastheman.com/2021/09/21/msvc/) which explains the MSVC ABI for pointers to member functions in some detail.

File: src/lib/netlist/plib/ppmf.h (hunk 2 above)
Comment (couriersud) [reply src/lib/netlist/plib/ppmf.h:8]: Strange. Will be fixed.

File: src/lib/netlist/plib/ppmf.h (hunk 3 above)
Comment (couriersud) [reply src/lib/netlist/plib/ppmf.h:37]: Will be fixed with next commit.

File: src/lib/netlist/core/core_device.h (hunk 4 above)
Comment (couriersud) [reply src/lib/netlist/core/core_device.h:36]: I have removed the bool opeator to align the design with `delegate` from `delegate.h`. `delegate`does not define an `explicit operator bool`.

Comment (cuavas) [reply src/lib/netlist/core/core_device.h:36]: Yeah, but that isn’t necessarily a good thing.  MAME’s `delegate` lacks an `explicit operator bool` for two reasons:
* Before C++11, if you had `operator bool` you could end up accidentally casting to integer types when you didn’t want to (leading to developer frustration), and if you had `explicit operator bool` you needed to explicitly cast to `bool` in places like control statement conditions.  It was often considered more trouble than it was worth.  C++11 changed the rules so that in certain contexts, the `explicit operator bool` will be used automatically, making it easier to work with.  The `delegate` predates C++11 and hasn’t had an `explicit operator bool` added since then.
* I haven’t just added `explicit operator bool` as a synonym for `isnull` because I haven’t checked the exact behaviour of `isnull()` when late binding is involved.  I wouldn’t want to add an `explicit operator bool` with confusing semantics.
* Some people seem to have an aversion to every using `operator bool` at all, and won’t use it even when it’s the idiomatic way to test something.

If you can implement `explicit operator bool` for PPMF in an intuitive way, I wouldn’t consider `delegate` lacking an equivalent to be a good reason not to.

File: src/lib/netlist/plib/ptests.h (hunk 1 above)
Comment (couriersud) [reply src/lib/netlist/plib/ptests.h:54]: I had issues with getting overloaded `<<` stream operators to compile with apple clang. This is a left-over. I will remove std::string and test the compile again. Afterwards I will commit.

> It’s good if some of the issues in PPMF can be resolved.
> 
>     * Have you fully exercised this for a target using the ARM variant of the Itanium ABI (e.g. ARM, AArch64, or WebAssembly)?

No. It would be great if somebody could point me to an image I can e.g. use with QEMU to compile netlist. In the mean time it would be great if somebody with access to such a system could do.
```
cd src/lib/netlist/build
make
./nltool --cmd tests

>     * At a glance, I didn’t notice provision for targets where function pointers point to descriptors (e.g. AIX/WinNT PPC, Linux/AIX PPC64, Itanium, etc.).  Are you catering for this?

Please see above. 
 
>     * Did you consider walking resolved PLT entries and out-of-line virtual call stubs used with MSVC ABI to reduce overhead?

Yes. The code is currently working and I will consider this when mame will compile under MSVC again. For some reason (compiler bug) this is currently not the case.
 
>     * I take it you’ve read [this](https://rants.vastheman.com/2021/09/21/msvc/) which explains the MSVC ABI for pointers to member functions in some detail.

Will do :-) prior to implementing resolved PLT.

Comment (cuavas) [reply src/lib/netlist/plib/ptests.h:54]: How small/isolated can you make the PPMF tests themselves?  A Raspberry Pi running Linux can be used for testing small stuff against the ARM variant of the Itanium ABI.

File: src/lib/netlist/core/core_device.h (hunk 4 above)
Comment (couriersud) [reply src/lib/netlist/core/core_device.h:36]: I removed it. No problem adding it again. Would be great if I can do this in a separate PR since I have other stuff I'd like to commit and waiting for this PR to be applied.

File: src/lib/netlist/plib/ptests.h (hunk 1 above)
Comment (couriersud) [reply src/lib/netlist/plib/ptests.h]: The standalone netlist build is pretty small. I anyhow need an replacement PI 4 for my homeautomation. The PI 3 is now a couple of years old. 
But ... there aren't any PIs available at reasonable prices. Once I get one I first use it to test the code.

File: src/lib/netlist/core/core_device.h (hunk 4 above)
Comment (cuavas) [reply src/lib/netlist/core/core_device.h:36]: > Would be great if I can do this in a separate PR since I have other stuff I'd like to commit and waiting for this PR to be applied.

I’d still like to see this actually tested on Itanium ARM variant, since that’s a key part of #8590.  Any of the following will do:
* An M1 Mac
* Emscripten build environment on Linux or Windows (can netlist library be built standalone with emmake wrapper?  e.g. see [how MAME is built for WebAssembly](https://docs.mamedev.org/initialsetup/compilingmame.html#emscripten-javascript-and-html))
* If the PPMF tests can be isolated so the rest of the netlist stuff doesn’t need to be built, a Raspberry Pi running Linux, or even one of those Chinese MIPS/Linux hand-helds sold as emulation devices

File: src/lib/netlist/plib/ptests.h (hunk 1 above)
Comment (cuavas) [reply src/lib/netlist/plib/ptests.h]: > The standalone netlist build is pretty small. I anyhow need an replacement PI 4 for my homeautomation. The PI 3 is now a couple of years old.

A Pi3 should be fine just for testing PPMF though.  (I’d argue a Pi3 is a better choice than a Pi4 for a lot of applications, just because of the lower power consumption and heat output.)

> But ... there aren't any PIs available at reasonable prices. Once I get one I first use it to test the code.

Yeah, scalpers ruin everything.  I expect at least a few other MAME developers do have Pi models with build environments set up that they could build a minimal test on, though.

File: src/lib/netlist/core/core_device.h [hunk 5]
```diff
@@ -1,4 +1,4 @@
-// license:BSD-3-Clause
+	// license:BSD-3-Clause
```
Comment (cuavas) [inline src/lib/netlist/core/core_device.h:1]: This seems to be an accidental indent.

File: src/lib/netlist/plib/ppmf.h [hunk 6]
```diff
@@ -106,45 +64,53 @@ namespace plib {
...
+			(ci::mingw() && !ci::m64())                                          ? PPMF_TYPE_PMF : // Dropped support for mingw32 < 407 PPMF_TYPE_INTERNAL_ITANIUM :
 			((ci::type() == ci_compiler::CLANG || ci::type() == ci_compiler::GCC)
 				&& (ci::arch() == ci_arch::MIPS
 					|| ci::arch() == ci_arch::ARM
-					|| ci::os() == ci_os::EMSCRIPTEN))                           ? 2 :
-			(ci::type() == ci_compiler::CLANG || ci::type() == ci_compiler::GCC) ? 1 :
-			(ci::type() == ci_compiler::MSC && ci::m64()) ?                        3 :
-																				   0
+					|| ci::os() == ci_os::EMSCRIPTEN))                           ? PPMF_TYPE_INTERNAL_ARM :
+			(ci::type() == ci_compiler::CLANG || ci::type() == ci_compiler::GCC) ? PPMF_TYPE_INTERNAL_ITANIUM :
```
Comment (cuavas) [inline src/lib/netlist/plib/ppmf.h:76]: Just noticed this - are you checking for clang compiling for MSVC ABI (e.g. using `clang-cl` wrapper)? In that situation, you need to use MSVC ABI but still avoid casting pointers to member functions across virtual inheritance relationships as clang doesn't support that MSVC extension.

Comment (couriersud) [reply src/lib/netlist/plib/ppmf.h:76]: Could you provide an example of which defines are set by clang-cl to identify the build?

Comment (cuavas) [reply src/lib/netlist/plib/ppmf.h:76]: Both `_MSC_VER` and `__clang__` are defined in that situation.  For example the situation is tested for to avoid attempting a test that only works with MSVC itself here: https://github.com/mamedev/mame/blob/mame0243/src/emu/validity.cpp#L1415

(This configuration is fairly popular with people who like the Visual Studio debugger, but want to avoid the long compile times and poor code generation of MSVC.)

File: src/lib/netlist/core/core_device.h (hunk 4 above)
Comment (couriersud) [reply src/lib/netlist/core/core_device.h]: Here we go. I'll commit the changes to support emscripten with `make emsdk` in a second:

```
emrun  --browser chrome nltool.html -c tests
Starting browser: /usr/bin/google-chrome-stable --enable-nacl --enable-pnacl --disable-restore-session-state --enable-webgl --no-default-browser-check --no-first-run --allow-file-access-from-files http://localhost:6931/nltool.html?-c&tests
======================================
Running 9 tests
======================================
pstring::conversion:
	OK: putf8string("Общая ком") == putf8string(putf16string(putf8string("Общая ком")))
	OK: putf8string("Общая ком") == putf8string(putf16string("Общая ком"))
pfunction::operators:
	OK: 1.0 == plib::pfunction<double>("1==1")()
	OK: 1.0 == plib::pfunction<double>("1 *0 == 2-1-1")()
	OK: 1.0 == plib::pfunction<double>("0!=1")()
	OK: 1.0 == plib::pfunction<double>("0<1")()
	OK: 1.0 == plib::pfunction<double>("1>0")()
	OK: 1.0 == plib::pfunction<double>("0<=1")()
	OK: 1.0 == plib::pfunction<double>("1>=0")()
	OK: 1.0 == plib::pfunction<double>("1<=1")()
	OK: 1.0 == plib::pfunction<double>("1>=1")()
	OK: 1.0 == plib::pfunction<double>("0!=a", {"a"})({1.0})
pfunction::func_if:
	OK: 2.0 == plib::pfunction<double>("if(1>0, 2, 0)")()
	OK: 3.0 == plib::pfunction<double>("if(0>1, 2, 3)")()
	OK: 2.0 == plib::pfunction<double>("if(sin(1)>0, 2, 3)")()
	OK: 1.0 == plib::pfunction<double>("if(A2>2.5, 0-A1, (0.07-(0.005*A1))*if(A0>2.5,1,0-1))", {"A0","A1","A2"})({1.0,-1.0,3.0})
	OK: -0.065 == plib::pfunction<double>("if(A2>2.5, 0-A1, (0.07-(0.005*A1))*if(A0>2.5,1,0-1))", {"A0","A1","A2"})({1.0,1.0,1.0})
	OK: 0.065 == plib::pfunction<double>("if(A2>2.5, 0-A1, (0.07-(0.005*A1))*if(A0>2.5,1,0-1))", {"A0","A1","A2"})({3.0,1.0,1.0})
	OK: 1.0 == plib::pfunction<double>("0!=a", {"a"})({1.0}) == true
pfunction::unary_minus:
	OK: 1.0 == plib::pfunction<double>("-1>-2")()
	OK: 12.0 == plib::pfunction<double>("(-3)*(-4)")()
	OK: 12.0 == plib::pfunction<double>("(-3)*-4")()
	OK: 12.0 == plib::pfunction<double>("-3*-4")()
	OK: -3.0 == plib::pfunction<double>("-A0", {"A0"})({3.0})
	OK: -9.0 == plib::pfunction<double>("3*-trunc(3.2)")()
	OK: -18.0 == plib::pfunction<double>("3*-(3*2)")()
	OK: -12.0 == plib::pfunction<double>("3*-(2*1)^2")()
	OK: got no exception for plib::pfunction<double>("(-3)")()
pfunction::expect_throw:
	OK: got plib::pexception for plib::pfunction<double>("(3, 4)")()
	OK: got plib::pexception for plib::pfunction<double>("((3)")()
	OK: got plib::pexception for plib::pfunction<double>("(3))")()
pmfp_test_complex_return::multibase_test:
	OK: f() == ret_t(static_cast<void *>(static_cast<a *>(&obj)), 1)
	OK: g_ret == ret_t(static_cast<void *>(static_cast<b *>(&obj)), 2)
	OK: g_ret == h()
	OK: g_ret == f()
	OK: f1_ret.first == f2_ret.first
	OK: f1_ret.second == 3
	OK: f2_ret.second == 4
	OK: f1_ret.first == f2_ret.first
	OK: f1_ret.second == 13
	OK: f2_ret.second == 14
	OK: static_cast<void *>(static_cast<vb *>(&obj2)) != static_cast<void *>(static_cast<vd1 *>(&obj2))
	OK: static_cast<void *>(static_cast<vb *>(&obj2)) != static_cast<void *>(static_cast<vd2 *>(&obj2))
	OK: f().second == 8
	OK: f().second == 9
pmfp_test_simple_return::multibase_test:
	OK: fr == ret_t(static_cast<void *>(static_cast<a *>(&obj)), 1)
	OK: gr == ret_t(static_cast<void *>(static_cast<b *>(&obj)), 2)
	OK: gr == hr
	OK: gr == fr
	OK: f1_ret.first == f2_ret.first
	OK: f1_ret.second == 3
	OK: f2_ret.second == 4
	OK: f1_ret.first == f2_ret.first
	OK: f1_ret.second == 13
	OK: f2_ret.second == 14
	OK: static_cast<void *>(static_cast<vb *>(&obj2)) != static_cast<void *>(static_cast<vd1 *>(&obj2))
	OK: static_cast<void *>(static_cast<vb *>(&obj2)) != static_cast<void *>(static_cast<vd2 *>(&obj2))
	OK: fr.second == 8
	OK: fr.second == 9
test_late_pmfp::late_pmfp:
	OK: r == 1 == true
test_compile::compile:
	OK: mfp_PPMF_TYPE_PMF.isnull() == true
	OK: mfp_PPMF_TYPE_INTERNAL_ITANIUM.isnull() == true
	OK: mfp_PPMF_TYPE_INTERNAL_ARM.isnull() == true
	OK: mfp_PPMF_TYPE_INTERNAL_MSC.isnull() == true
	OK: "PPMF_TYPE_GNUC_PMF_CONV not supported on this build" != ""
	OK: plib::ppmf_internal::value == 3
```
All tests are successful. The last line shows that PPMF_TYPE_INTERNAL_ARM is used by default.

File: src/lib/netlist/plib/ppmf.h (hunk 6 above)
Comment (couriersud) [reply src/lib/netlist/plib/ppmf.h]: Supported now (see https://github.com/mamedev/mame/pull/9752/commits/49e7da33f600b61d84292bf66245ccccc068b2ad)

File: src/lib/netlist/plib/ppmf.h [hunk 7]
```diff
@@ -153,277 +119,341 @@ namespace plib {
...
+				func = *reinterpret_cast<generic_function *>(vtable_base + m_function + m_this_delta - 1);
 			}
 		}
 
 		// actual state
 		uintptr_t               m_function;         // first item can be one of two things:
 													//    if even, it's a pointer to the function
 													//    if odd, it's the byte offset into the vtable
-		int                     m_this_delta;       // delta to apply to the 'this' pointer
+		ptrdiff_t               m_this_delta;       // delta to apply to the 'this' pointer
```
Comment (cuavas) [inline src/lib/netlist/plib/ppmf.h:195]: This comment describing the standard Itanium ABI snuck through – it’s not correct for the ARM variant here.

File: src/lib/netlist/plib/ppmf.h [hunk 8]
```diff
@@ -153,277 +119,341 @@ namespace plib {
...
+			auto const *funcx = reinterpret_cast<std::uint8_t const *>(m_function);
+			// NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast,performance-no-int-to-ptr)
+			func = reinterpret_cast<generic_function>(std::uintptr_t(funcx));
+		}
+
+		// actual state
+		uintptr_t m_function;         // first item can be one of two things:
+													//    if even, it's a pointer to the function
+													//    if odd, it's the byte offset into the vtable
+		int       m_this_delta;       // delta to apply to the 'this' pointer
```
Comment (cuavas) [inline src/lib/netlist/plib/ppmf.h:250]: The copy/pasted comment is here, too – the first item is always a function pointer with the MSVC ABI.
