### PR TITLE
Fix several issues in DC-based HW

### LINKED ISSUE #8999: powervr2.cpp: kurucham corrupted Starfish-SD GFX logo
Given the typical green on bottom suspected culprit should be a YUV render taking wrong pitch width

### LINKED ISSUE #9000: naomi.cpp: jingystm black screen on boot
Does a work RAM buffer read at PC=0c04c2a8 R3=$c0cda28 to return 0x01, actual 0x11, cannot backtrace (missing irq gen somewhere likely)

### PR DESCRIPTION
**Pull request by angelosa**
Highlights:
- Streamlined logging across chips to use logmacro.h, removed popmessages and printfs in production code;
- Add missing include guards in header files;
- split Atomiswave into own file from naomi.cpp (dc_atomiswave.cpp);
- powervr2.cpp: YUV pitch follows U size, fixes #8999
- powervr2.cpp: move Elan related stuff back into naomi2_state;
- naomi.cpp: support for player 2 keyboard inputs;
- naomi.cpp: add proper inputs to alpilot/alpilotj and sstrkfgt;
- naomi.cpp: hookup lightgun for deathcox;
- naomi.cpp: make G2-DMA timings slightly more accurate (fixes sfz3ugd silent BGMs regression caused by implicit insta-DMAs)
- dc_g2if.cpp: wrote a device for G2 DMA interface, fixes #9000 ;
- dc_g2if.cpp: add E1/E2/DD channels thru template, add area protection, add illegal address and overflow exceptions (fixes loopchk g2 bus tests 0302 and 0303)
- aica.cpp: $2814 CA reads doesn't need shifting, fixes ADX repeating sample/hang bugs in many entries [Angelo Salese, MetalliC];
- powervr2.cpp: make ISP/TSP irq to be slower, fixes regression bug with Capcom fighters having frame hiccups [David Haywood, Angelo Salese]
- dc_atomiswave.cpp: converted aw_modem_r/_w to 32-bit, added 3p/4p inputs to ggisuka, expose EXID to an input/output ioports for future extensions;
- dc_atomiswave.cpp: extend xtrmhnt2 ALL.Net hack for -drc, move around state machine to derive ALL.Net external device mapping instead of driver_init fn, demote to MUP for obvious reasons;
- dc_atomiswave: add Area 1 mirrors, fix maxspeed title screen animation;
- [MT#8143](https://mametesters.org/view.php?id=8143) is fixed

New NOT_WORKING software list additions
---------------------------------------
dc.xml: DC Checker for Repair v2.05R (World), Loop Checker v1.00 (World), GD Drive Repair Program v0.1 (World) [Hidden Palace]

### CODE REVIEW

**Comment by DavidHaywood** [comment]
I don't want to be credited with any Naomi games promoted to working.

IMHO anything that runs so slow, on hardware where the emulation is so incomplete, where there are vastly better options, should not be promoted, it gives the project a bad reputation as it creates a false expectation.

When they can realistically run at full speed on a machine that exists, and have video emulation on par with other emulators, I'd consider it OK to make such claims.

If you want to anyway, go ahead, but please, keep my name 100% out of it, I don't want a reputation as somebody who misleads people.

**Comment by angelosa** [comment]
A few selected games have been promoted over the chance of being fully playable start to end, not crashing in attract/service mode for a good amount of time etc.
It’s the standard QA procedure and NAOMI isn’t a special HW we should treat differently.
I've also promoted a few things where video and sound don't impact the overall experience. There's a significant difference between these and something like Power Stone, where not having proper Z sort hampers with gameplay (i.e. chest lights covers player/enemy/objects display). 

> When they can realistically run at full speed on a machine that exists, and have video emulation on par with other emulators, I'd consider it OK to make such claims.

Animal Basket can be run at 100% on my end, it's also debatable about that using the MIG at all (it's a very simple game with no video bugs to my knowledge). And there were a few entries already without the MNW here, I've just applied the standard procedure not giving a good crap about performance: it never ever was a liability for marking anything as MNW.

I acknowledge that you want your name removed, but my bottom line is that we'll never ever move forward if we pre-emptively say everything is crap and don't give any chance of a "reward" for anybody willing to tackle remaining issues. 
A 6th gen system has already enough problems on its own.

**Comment by DavidHaywood** [comment]
> I acknowledge that you want your name removed, but my bottom line is that we'll never ever move forward if we pre-emptively say everything is crap and don't give any chance of a "reward" for anybody willing to tackle remaining issues.

I guess one of my points is you're denying that 'reward' from whoever puts in the final work to make these playable with systems people own, or are likely to own in the next 10 years.

Either way, yes, I'd prefer my name to be removed, otherwise people are going to come back to me and either congratulate me on it, or ask questions about it, and I wouldn't feel comfortable with either of those positions, because to me, it's a lie to call them working at this point.

**Comment by angelosa** [comment]
At this point I'm open to hear others opinions.
If I have to pre-emptively mark all the games in the drivers as MNW may as well do in this branch. 
imho performance isn't a liability for marking as such, but if the general consensus states otherwise may as well be properly ticketed into an issue too.

**Comment by DavidHaywood** [comment]
Honestly I'd keep them as demoted.

There are more games across the codebase that I would demote too.

Where MAME stands today it's a resource for people wanting to put out reissues of these games, it's important that we only declare something as working if it really works, and works well.

We're in this for the long game, rushing things to promotion doesn't help our cause.

One of the reasons things like MAME2003 are more of a problem than they should be is that we were declaring games as 'working' long, long before they were, so people are blind to the fact they're not really working and take it at face value that they are.  Take the Taito C-Chip games for example, none of them should really have been marked as working until the C-Chips were decapped, but instead the c-chip decapping moment gets overlooked because we claimed they were working back then.

File: src/mame/drivers/dc_atomiswave.cpp [hunk 1]
```diff
@@ -0,0 +1,1536 @@
...
+		{
+			addr += i;
+			break;
+		}
+	}
+
+	data >>= (i*8);
+
+	m_awflash->write(addr, data);
+}
```
Comment (cuavas) [inline src/mame/drivers/dc_atomiswave.cpp:463]: Would this whole thing be better to do as an 8-bit handler with a unit mask?

File: src/mame/drivers/naomi.cpp [hunk 2]
```diff
@@ -2635,15 +2035,63 @@ static INPUT_PORTS_START( naomi_mp )
...
+		// if anything is pressed, convert the 32-bit raw value to keycode
+		if(row != 0)
+		{
+			// base value x20
+			retval = i * 0x20;
+			for(int j = 0; j < 32; j++)
+			{
+				if(row & 1 << j)
+					return retval + j;
+			}
```
Comment (cuavas) [inline src/mame/drivers/naomi.cpp]: You’re doing `for(...)` and `if(...)` here when the rest of the file does `for (...)` and `if (...)`

Also, the use of `retval` is weird – it can only be assigned a non-zero value inside here, and there’s no way to fall off the end of the loop if it’s assigned a non-zero value.  It would be a lot cleared to declare `retval` inside the scope where it’s actually used and `return 0` at the end of the function.  Having it the way it is suggests `retval` may carry a meaningful value across loop iterations, but it doesn’t.

File: src/mame/machine/dc_g2if.h [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+	template <u8 ch> void tsel_w(offs_t offset, u32 data, u32 mem_mask = ~0);
+
+	template <u8 ch> u32 en_r();
+	template <u8 ch> void en_w(offs_t offset, u32 data, u32 mem_mask = ~0);
+
+	template <u8 ch> u32 st_r();
+	template <u8 ch> void st_w(offs_t offset, u32 data, u32 mem_mask = ~0);
+
+	template <u8 ch> u32 susp_r();
+	template <u8 ch> void susp_w(offs_t offset, u32 data, u32 mem_mask = ~0);
```
Comment (cuavas) [inline src/mame/machine/dc_g2if.h:90]: Please use `LlamaCase` for template parameters, to make it clear that they’re semantically different (e.g. tests/conditional branches on them are flattened at compile time).

File: src/mame/machine/dc_g2if.cpp [hunk 4]
```diff
@@ -0,0 +1,538 @@
...
+	   different security code & area protection);
+	- DMA starts should send DDT requests and being notified back to use this i/f implementation
+	  anyway. Exact purpose is unknown, maybe it's for granting use of the bus?
+
+**************************************************************************************************/
+
+#include "emu.h"
+#include "dc_g2if.h"
+
+#define LOG_WARN    (1U << 0)
```
Comment (cuavas) [inline src/mame/machine/dc_g2if.cpp:23]: You shouldn’t use bit zero for a user-defined log constant – it’s used for `LOG_GENERAL` and the abbreviated `LOG` macro in logmacro.h itself.

File: src/mame/machine/dc_g2if.cpp [hunk 5]
```diff
@@ -0,0 +1,538 @@
...
+		m_dma[ch].tsel = 0;
+		m_dma[ch].hw_trigger = false;
+		m_dma[ch].end_timer->adjust(attotime::never);
+	}
+}
+
+void dc_g2if_device::device_timer(emu_timer &timer, device_timer_id id, int param, void *ptr)
+{
+	u8 channel = (u8)id;
+	bool dma_result = (bool)(param == 1);
```
Comment (cuavas) [inline src/mame/machine/dc_g2if.cpp:127]: The cast to `bool` here is pointless – a comparison produces a `bool` result directly.

File: src/mame/machine/dccons.cpp [hunk 6]
```diff
@@ -6,27 +6,41 @@
...
 #include "includes/dc.h"
 #include "cpu/sh/sh4.h"
 #include "sound/aica.h"
 #include "includes/dccons.h"
 
-#define ATAPI_CYCLES_PER_SECTOR (5000)  // TBD for Dreamcast
+// TODO: fine grain this value
+#define ATAPI_CYCLES_PER_SECTOR (5000)
+
+#define LOG_WARN    (1U << 0)
```
Comment (cuavas) [inline src/mame/machine/dccons.cpp:35]: Same as other file, using bit zero will cause confusion.

File: src/mame/machine/dccons.cpp [hunk 7]
```diff
@@ -67,28 +81,33 @@ TIMER_CALLBACK_MEMBER(dc_cons_state::atapi_xfer_end )
...
-		ddtdata.channel= 0;
-		ddtdata.mode= -1;       // copy from/to buffer
-		printf("ATAPI: DMA one sector to %x, %x remaining\n", atapi_xferbase, atapi_xferlen);
+		ddtdata.direction = 1;    // 0 source to buffer, 1 buffer to destination
+		ddtdata.channel = 0;
+		ddtdata.mode = -1;       // copy from/to buffer
+		LOGXFER("G1 I/F ATAPI: DMA one sector to %x, %x remaining\n",
+			machine().describe_context(),
+			atapi_xferbase, atapi_xferlen
+		);
```
Comment (cuavas) [inline src/mame/machine/dccons.cpp:93]: Format string doesn’t match arguments.

File: src/mame/machine/gdrom.cpp [hunk 8]
```diff
@@ -9,6 +9,18 @@
 #include "emu.h"
 #include "gdrom.h"
 
+#define LOG_WARN    (1U << 0)
```
Comment (cuavas) [inline src/mame/machine/gdrom.cpp:12]: Another file inappropriately using bit zero with the logging macros.

File: src/mame/machine/gdrom.cpp [hunk 9]
```diff
@@ -162,29 +174,30 @@ void gdrom_device::ExecCommand()
...
 			break;
 
 		case 0x12: // SET_MODE
-			logerror("GDROM: SET_MODE\n");
 			m_phase = SCSI_PHASE_DATAOUT;
 			m_status_code = SCSI_STATUS_CODE_GOOD;
 			//transferOffset = command[2];
 			m_transfer_length = SCSILengthFromUINT8( &command[ 4 ] );
-			printf("SET_MODE %02x %02x\n",command[2],command[4]);
+			LOGCMD("%s: SET_MODE %02x %02x\n", tag(), command[2], command[4]);
```
Comment (cuavas) [inline src/mame/machine/gdrom.cpp:193]: `logerror` always includes the device tag.

File: src/mame/machine/gdrom.cpp [hunk 10]
```diff
@@ -196,15 +209,20 @@ void gdrom_device::ExecCommand()
...
+					throw emu_fatalerror("GDROM: Unhandled data_select %d", data_select);
 				}
 
-				printf("GDROM: CD_READ at LBA %x for %d blocks (%d bytes, read type %d, data select %d)\n", m_lba, m_blocks, m_blocks * m_sector_bytes, read_type, data_select);
+				LOGCMD("%s: CD_READ %02x %02x\n", tag(), command[2], command[4]);
+
+				LOGCMD("%s: CD_READ at LBA %x for %d blocks (%d bytes, read type %d, data select %d)\n",
+					tag(), m_lba, m_blocks,
+					m_blocks * m_sector_bytes, read_type, data_select
+				);
```
Comment (cuavas) [inline src/mame/machine/gdrom.cpp:225]: More things redundantly adding the tag.  There are more of these further down, too.

File: src/mame/video/powervr2.cpp [hunk 11]
```diff
@@ -1054,9 +1071,19 @@ void powervr2_device::startrender_w(address_space &space, uint32_t data)
...
+			// TODO: exact timing of this
+			// hacky end of render delay for Capcom games, otherwise they works at ~1/10 speed.
+			// 500k is definitely too slow for them: it fires the isp/tsp completion at
+			// vbl-in and expect that it completes after some time that vbl-out kicks in,
+			// in order to have enough time to execute logic stuff in the meantime.
+//          const u64 isp_completion = sanitycount * 25 + 500000;
+			const u64 isp_completion = sanitycount * 25 + 2000000;
+			LOGIRQ("%s: [%d] ISP end of render start %d in %d cycles\n",
+				tag(), screen().frame_number(), screen().vpos(), isp_completion
+			);
```
Comment (cuavas) [inline src/mame/video/powervr2.cpp:1085]: Another redundant tag in a log message.

File: src/mame/video/powervr2.cpp [hunk 12]
```diff
@@ -1447,10 +1474,15 @@ void powervr2_device::ta_list_init_w(uint32_t data)
...
-					tag(), ta_ol_base, ta_ol_limit, ta_isp_base, ta_isp_limit, ta_alloc_ctrl, ta_next_opb_init);
-#endif
+
+		LOGTACMD("%s: list init ol=(%08x, %08x) isp=(%08x, %08x), alloc=%08x obp=%08x\n",
+			tag(),
+			ta_ol_base, ta_ol_limit,
+			ta_isp_base, ta_isp_limit,
+			ta_alloc_ctrl,
+			ta_next_opb_init
+		);
```
Comment (cuavas) [inline src/mame/video/powervr2.cpp:1484]: Yet another.

File: src/mame/video/powervr2.cpp [hunk 13]
```diff
@@ -1717,35 +1744,35 @@ void powervr2_device::sb_pdapro_w(offs_t offset, uint32_t data, uint32_t mem_mas
...
-//  printf("OPMV %d\n",screen().vpos());
+	LOGIRQ("%s: [%d] EOXFER OPMV %d\n", tag(), screen().frame_number(), screen().vpos());
 
 	irq_cb(EOXFER_OPMV_IRQ);
 }
 
 TIMER_CALLBACK_MEMBER(powervr2_device::transfer_translucent_list_irq)
 {
-//  printf("TRLST %d\n",screen().vpos());
+	LOGIRQ("%s: [%d] EOXFER TRLST %d\n", tag(), screen().frame_number(), screen().vpos());
```
Comment (cuavas) [inline src/mame/video/powervr2.cpp:1761]: Still more redundant tags.

File: src/mame/drivers/naomi.cpp (hunk 2 above)
Comment (angelosa) [reply src/mame/drivers/naomi.cpp]: Not really touched this part but yes, I see your point here.

Comment (cuavas) [reply src/mame/drivers/naomi.cpp]: Oh was that moved from machine/naomi.cpp?  It’s a bit confusing working out what’s just shuffled and what’s changed.

File: src/mame/drivers/dc_atomiswave.cpp (hunk 1 above)
Comment (angelosa) [reply src/mame/drivers/dc_atomiswave.cpp:463]: Haven't touched this part either but yeah good call: `macronix_29l001mc_device` inherits from `intelfsh8_device` which shouldn't need this trampoline at all.

**Comment by angelosa** [comment]
Addressed code review.

File: src/mame/drivers/dc_atomiswave.cpp [hunk 14]
```diff
@@ -0,0 +1,1511 @@
...
+// note: games with AW-NET features, i.e. NGBC or KOF NW, have "CUSTOMER ID" data (shown in NETWORK SETTINGS) in ROM @ 7FE000 (not encrypted, 8 bytes of data followed by 2 bytes of bytesumm)
+// EN cartridges have this area empty (FF-filled), i.e. AW-NET features not used.
+// JP cartridges have it filled with unique ID, which also means dumps of several JP cartridges will differ by this few bytes.
+
+void atomiswave_state::init_atomiswave()
+{
+	uint64_t *ROM = (uint64_t *)memregion("awflash")->base();
+
+	// patch out long startup delay
+	ROM[0x98e/8] = (ROM[0x98e/8] & 0xffffffffffffU) | (uint64_t)0x0009<<48;
```
Comment (angelosa) [inline src/mame/drivers/dc_atomiswave.cpp:878]: Do we need this? It doesn't seem to make any difference but unsure about what romset is referring to.

Comment (rb6502) [reply src/mame/drivers/dc_atomiswave.cpp:878]: That's in the BIOS, it's a delay loop to slow down the boot logo.  Pre-DRC at least it was extremely noticeable.

Comment (angelosa) [reply src/mame/drivers/dc_atomiswave.cpp:878]: Ah right, it reads from flash file if it's present from NVRAM. I'll add a note.
